/**
 * List of Australian horse racing tracks/venues
 * Organized by state for easier selection
 */
export const AUSTRALIAN_RACE_TRACKS = [
  // New South Wales
  { value: 'randwick', label: 'Randwick', state: 'NSW' },
  { value: 'rosehill', label: 'Rosehill Gardens', state: 'NSW' },
  { value: 'warwick-farm', label: 'Warwick Farm', state: 'NSW' },
  { value: 'canterbury', label: 'Canterbury Park', state: 'NSW' },
  { value: 'kembla-grange', label: 'Kembla Grange', state: 'NSW' },
  { value: 'newcastle', label: 'Newcastle', state: 'NSW' },
  { value: 'gosford', label: 'Gosford', state: 'NSW' },
  { value: 'hawkesbury', label: 'Hawkesbury', state: 'NSW' },
  { value: 'wyong', label: 'Wyong', state: 'NSW' },
  { value: 'kempsey', label: 'Kempsey', state: 'NSW' },
  { value: 'port-macquarie', label: 'Port Macquarie', state: 'NSW' },
  { value: 'taree', label: 'Taree', state: 'NSW' },
  { value: 'coffs-harbour', label: 'Coffs Harbour', state: 'NSW' },
  { value: 'grafton', label: 'Grafton', state: 'NSW' },
  { value: 'lismore', label: 'Lismore', state: 'NSW' },
  { value: 'ballina', label: 'Ballina', state: 'NSW' },
  { value: 'wagga-wagga', label: 'Wagga Wagga', state: 'NSW' },
  { value: 'albury', label: 'Albury', state: 'NSW' },
  { value: 'goulburn', label: 'Goulburn', state: 'NSW' },
  { value: 'nowra', label: 'Nowra', state: 'NSW' },
  { value: 'sapphire-coast', label: 'Sapphire Coast', state: 'NSW' },
  { value: 'gunnedah', label: 'Gunnedah', state: 'NSW' },
  { value: 'tamworth', label: 'Tamworth', state: 'NSW' },
  { value: 'armidale', label: 'Armidale', state: 'NSW' },
  { value: 'moree', label: 'Moree', state: 'NSW' },
  { value: 'narromine', label: 'Narromine', state: 'NSW' },
  { value: 'dubbo', label: 'Dubbo', state: 'NSW' },
  { value: 'orange', label: 'Orange', state: 'NSW' },
  { value: 'bathurst', label: 'Bathurst', state: 'NSW' },
  { value: 'mudgee', label: 'Mudgee', state: 'NSW' },
  { value: 'parkes', label: 'Parkes', state: 'NSW' },
  { value: 'forbes', label: 'Forbes', state: 'NSW' },
  { value: 'cowra', label: 'Cowra', state: 'NSW' },
  { value: 'young', label: 'Young', state: 'NSW' },
  { value: 'gundagai', label: 'Gundagai', state: 'NSW' },
  { value: 'corowa', label: 'Corowa', state: 'NSW' },
  { value: 'deniliquin', label: 'Deniliquin', state: 'NSW' },
  { value: 'griffith', label: 'Griffith', state: 'NSW' },
  { value: 'leeton', label: 'Leeton', state: 'NSW' },
  { value: 'narrandera', label: 'Narrandera', state: 'NSW' },
  { value: 'broken-hill', label: 'Broken Hill', state: 'NSW' },

  // Victoria
  { value: 'flemington', label: 'Flemington', state: 'VIC' },
  { value: 'caulfield', label: 'Caulfield', state: 'VIC' },
  { value: 'moonee-valley', label: 'Moonee Valley', state: 'VIC' },
  { value: 'sandown', label: 'Sandown', state: 'VIC' },
  { value: 'geelong', label: 'Geelong', state: 'VIC' },
  { value: 'ballarat', label: 'Ballarat', state: 'VIC' },
  { value: 'bendigo', label: 'Bendigo', state: 'VIC' },
  { value: 'werribee', label: 'Werribee', state: 'VIC' },
  { value: 'cranbourne', label: 'Cranbourne', state: 'VIC' },
  { value: 'pakenham', label: 'Pakenham', state: 'VIC' },
  { value: 'moe', label: 'Moe', state: 'VIC' },
  { value: 'sale', label: 'Sale', state: 'VIC' },
  { value: 'bairnsdale', label: 'Bairnsdale', state: 'VIC' },
  { value: 'traralgon', label: 'Traralgon', state: 'VIC' },
  { value: 'warrnambool', label: 'Warrnambool', state: 'VIC' },
  { value: 'hamilton', label: 'Hamilton', state: 'VIC' },
  { value: 'colac', label: 'Colac', state: 'VIC' },
  { value: 'camperdown', label: 'Camperdown', state: 'VIC' },
  { value: 'terang', label: 'Terang', state: 'VIC' },
  { value: 'mortlake', label: 'Mortlake', state: 'VIC' },
  { value: 'casterton', label: 'Casterton', state: 'VIC' },
  { value: 'horsham', label: 'Horsham', state: 'VIC' },
  { value: 'stawell', label: 'Stawell', state: 'VIC' },
  { value: 'ararat', label: 'Ararat', state: 'VIC' },
  { value: 'avoca', label: 'Avoca', state: 'VIC' },
  { value: 'stony-creek', label: 'Stony Creek', state: 'VIC' },
  { value: 'yarram', label: 'Yarram', state: 'VIC' },
  { value: 'kilmore', label: 'Kilmore', state: 'VIC' },
  { value: 'kyneton', label: 'Kyneton', state: 'VIC' },
  { value: 'echuca', label: 'Echuca', state: 'VIC' },
  { value: 'swan-hill', label: 'Swan Hill', state: 'VIC' },
  { value: 'kerang', label: 'Kerang', state: 'VIC' },
  { value: 'mildura', label: 'Mildura', state: 'VIC' },
  { value: 'oakbank', label: 'Oakbank', state: 'VIC' },
  { value: 'murtoa', label: 'Murtoa', state: 'VIC' },
  { value: 'warracknabeal', label: 'Warracknabeal', state: 'VIC' },
  { value: 'nhill', label: 'Nhill', state: 'VIC' },
  { value: 'edenhope', label: 'Edenhope', state: 'VIC' },
  { value: 'naracoorte', label: 'Naracoorte', state: 'VIC' },
  { value: 'penola', label: 'Penola', state: 'VIC' },
  { value: 'mount-gambier', label: 'Mount Gambier', state: 'VIC' },

  // Queensland
  { value: 'eagle-farm', label: 'Eagle Farm', state: 'QLD' },
  { value: 'doomben', label: 'Doomben', state: 'QLD' },
  { value: 'caloundra', label: 'Caloundra', state: 'QLD' },
  { value: 'sunshine-coast', label: 'Sunshine Coast', state: 'QLD' },
  { value: 'gold-coast', label: 'Gold Coast', state: 'QLD' },
  { value: 'ipswich', label: 'Ipswich', state: 'QLD' },
  { value: 'toowoomba', label: 'Toowoomba', state: 'QLD' },
  { value: 'warwick', label: 'Warwick', state: 'QLD' },
  { value: 'dalby', label: 'Dalby', state: 'QLD' },
  { value: 'gympie', label: 'Gympie', state: 'QLD' },
  { value: 'bundaberg', label: 'Bundaberg', state: 'QLD' },
  { value: 'rockhampton', label: 'Rockhampton', state: 'QLD' },
  { value: 'mackay', label: 'Mackay', state: 'QLD' },
  { value: 'townsville', label: 'Townsville', state: 'QLD' },
  { value: 'cairns', label: 'Cairns', state: 'QLD' },
  { value: 'innisfail', label: 'Innisfail', state: 'QLD' },
  { value: 'mount-isa', label: 'Mount Isa', state: 'QLD' },
  { value: 'longreach', label: 'Longreach', state: 'QLD' },
  { value: 'roma', label: 'Roma', state: 'QLD' },
  { value: 'charleville', label: 'Charleville', state: 'QLD' },
  { value: 'cunnamulla', label: 'Cunnamulla', state: 'QLD' },
  { value: 'thangool', label: 'Thangool', state: 'QLD' },
  { value: 'biloela', label: 'Biloela', state: 'QLD' },
  { value: 'emerald', label: 'Emerald', state: 'QLD' },
  { value: 'clermont', label: 'Clermont', state: 'QLD' },
  { value: 'charters-towers', label: 'Charters Towers', state: 'QLD' },
  { value: 'bowen', label: 'Bowen', state: 'QLD' },
  { value: 'airlie-beach', label: 'Airlie Beach', state: 'QLD' },
  { value: 'yeppoon', label: 'Yeppoon', state: 'QLD' },
  { value: 'gladstone', label: 'Gladstone', state: 'QLD' },
  { value: 'maryborough', label: 'Maryborough', state: 'QLD' },
  { value: 'nanango', label: 'Nanango', state: 'QLD' },
  { value: 'kilcoy', label: 'Kilcoy', state: 'QLD' },
  { value: 'beaudesert', label: 'Beaudesert', state: 'QLD' },
  { value: 'grafton', label: 'Grafton', state: 'QLD' },

  // South Australia
  { value: 'morphettville', label: 'Morphettville', state: 'SA' },
  { value: 'gawler', label: 'Gawler', state: 'SA' },
  { value: 'murray-bridge', label: 'Murray Bridge', state: 'SA' },
  { value: 'strathalbyn', label: 'Strathalbyn', state: 'SA' },
  { value: 'victor-harbor', label: 'Victor Harbor', state: 'SA' },
  { value: 'port-lincoln', label: 'Port Lincoln', state: 'SA' },
  { value: 'whyalla', label: 'Whyalla', state: 'SA' },
  { value: 'port-augusta', label: 'Port Augusta', state: 'SA' },
  { value: 'port-pirie', label: 'Port Pirie', state: 'SA' },
  { value: 'clare', label: 'Clare', state: 'SA' },
  { value: 'kapunda', label: 'Kapunda', state: 'SA' },
  { value: 'gawler', label: 'Gawler', state: 'SA' },
  { value: 'balaklava', label: 'Balaklava', state: 'SA' },
  { value: 'burra', label: 'Burra', state: 'SA' },
  { value: 'jamestown', label: 'Jamestown', state: 'SA' },
  { value: 'peterborough', label: 'Peterborough', state: 'SA' },
  { value: 'orroroo', label: 'Orroroo', state: 'SA' },
  { value: 'quorn', label: 'Quorn', state: 'SA' },
  { value: 'hawker', label: 'Hawker', state: 'SA' },
  { value: 'coober-pedy', label: 'Coober Pedy', state: 'SA' },

  // Western Australia
  { value: 'ascot', label: 'Ascot', state: 'WA' },
  { value: 'belmont', label: 'Belmont Park', state: 'WA' },
  { value: 'pinjarra', label: 'Pinjarra', state: 'WA' },
  { value: 'bunbury', label: 'Bunbury', state: 'WA' },
  { value: 'albany', label: 'Albany', state: 'WA' },
  { value: 'esperance', label: 'Esperance', state: 'WA' },
  { value: 'kalgoorlie', label: 'Kalgoorlie', state: 'WA' },
  { value: 'geraldton', label: 'Geraldton', state: 'WA' },
  { value: 'carnarvon', label: 'Carnarvon', state: 'WA' },
  { value: 'broome', label: 'Broome', state: 'WA' },
  { value: 'port-hedland', label: 'Port Hedland', state: 'WA' },
  { value: 'newman', label: 'Newman', state: 'WA' },
  { value: 'northam', label: 'Northam', state: 'WA' },
  { value: 'york', label: 'York', state: 'WA' },
  { value: 'toodyay', label: 'Toodyay', state: 'WA' },
  { value: 'moore', label: 'Moore', state: 'WA' },
  { value: 'wongan-hills', label: 'Wongan Hills', state: 'WA' },
  { value: 'merredin', label: 'Merredin', state: 'WA' },
  { value: 'kellerberrin', label: 'Kellerberrin', state: 'WA' },
  { value: 'narrogin', label: 'Narrogin', state: 'WA' },
  { value: 'katanning', label: 'Katanning', state: 'WA' },
  { value: 'mount-barker', label: 'Mount Barker', state: 'WA' },
  { value: 'manjimup', label: 'Manjimup', state: 'WA' },
  { value: 'collie', label: 'Collie', state: 'WA' },
  { value: 'harvey', label: 'Harvey', state: 'WA' },
  { value: 'mandurah', label: 'Mandurah', state: 'WA' },
  { value: 'wagin', label: 'Wagin', state: 'WA' },
  { value: 'kulin', label: 'Kulin', state: 'WA' },
  { value: 'hyden', label: 'Hyden', state: 'WA' },
  { value: 'lake-grace', label: 'Lake Grace', state: 'WA' },
  { value: 'ravensthorpe', label: 'Ravensthorpe', state: 'WA' },
  { value: 'ongerup', label: 'Ongerup', state: 'WA' },
  { value: 'jerramungup', label: 'Jerramungup', state: 'WA' },
  { value: 'bremer-bay', label: 'Bremer Bay', state: 'WA' },
  { value: 'denmark', label: 'Denmark', state: 'WA' },
  { value: 'mount-barker', label: 'Mount Barker', state: 'WA' },

  // Tasmania
  { value: 'elwick', label: 'Elwick', state: 'TAS' },
  { value: 'launceston', label: 'Launceston', state: 'TAS' },
  { value: 'devonport', label: 'Devonport', state: 'TAS' },
  { value: 'spreyton', label: 'Spreyton', state: 'TAS' },
  { value: 'hobart', label: 'Hobart', state: 'TAS' },
  { value: 'longford', label: 'Longford', state: 'TAS' },
  { value: 'scottsdale', label: 'Scottsdale', state: 'TAS' },
  { value: 'st-helens', label: 'St Helens', state: 'TAS' },
  { value: 'wynyard', label: 'Wynyard', state: 'TAS' },
  { value: 'burnie', label: 'Burnie', state: 'TAS' },
  { value: 'king-island', label: 'King Island', state: 'TAS' },
  { value: 'flinders-island', label: 'Flinders Island', state: 'TAS' },

  // Northern Territory
  { value: 'fannie-bay', label: 'Fannie Bay', state: 'NT' },
  { value: 'alice-springs', label: 'Alice Springs', state: 'NT' },
  { value: 'katherine', label: 'Katherine', state: 'NT' },
  { value: 'tennant-creek', label: 'Tennant Creek', state: 'NT' },
  { value: 'pine-creek', label: 'Pine Creek', state: 'NT' },
  { value: 'adelaide-river', label: 'Adelaide River', state: 'NT' },
  { value: 'humpty-doo', label: 'Humpty Doo', state: 'NT' },
  { value: 'darwin', label: 'Darwin', state: 'NT' },

  // Australian Capital Territory
  { value: 'canberra', label: 'Canberra', state: 'ACT' },
] as const;

export type TrackValue = typeof AUSTRALIAN_RACE_TRACKS[number]['value'];

/**
 * Get tracks grouped by state
 */
export function getTracksByState() {
  const grouped: Record<string, typeof AUSTRALIAN_RACE_TRACKS> = {};
  AUSTRALIAN_RACE_TRACKS.forEach((track) => {
    if (!grouped[track.state]) {
      grouped[track.state] = [];
    }
    grouped[track.state].push(track);
  });
  return grouped;
}

/**
 * Get track label by value
 */
export function getTrackLabel(value: string | null | undefined): string {
  if (!value) return '';
  const track = AUSTRALIAN_RACE_TRACKS.find((t) => t.value === value);
  return track ? track.label : value;
}

